add lifecycle datasource
OpsLevel/terraform-provider-opslevel pull request #240
Opened 2024-03-26 19:42 UTC by taimoorgit

## Issues

https://github.com/OpsLevel/team-platform/issues/288

## Tophatting

```
data "opslevel_lifecycle" "l1" {
  filter {
    field = "alias"
    value = "generally_available"
  }
}

data "opslevel_lifecycle" "l2" {
  filter {
    field = "id"
    value = "Z2lkOi8vb3BzbGV2ZWwvTGlmZWN5Y2xlLzQ"
  }
}

output "o1" {
  value = data.opslevel_lifecycle.l1
}

output "o2" {
  value = data.opslevel_lifecycle.l2
}
```

```
Changes to Outputs:
  + o1 = {
      + alias       = "generally_available"
      + description = "Service is supporting features available to be used by all customers, and should be fully stable."
      + filter      = {
          + field = "alias"
          + value = "generally_available"
        }
      + id          = "Z2lkOi8vb3BzbGV2ZWwvTGlmZWN5Y2xlLzQ"
      + index       = 4
      + name        = "Generally Available"
    }
  + o2 = {
      + alias       = "generally_available"
      + description = "Service is supporting features available to be used by all customers, and should be fully stable."
      + filter      = {
          + field = "id"
          + value = "Z2lkOi8vb3BzbGV2ZWwvTGlmZWN5Y2xlLzQ"
        }
      + id          = "Z2lkOi8vb3BzbGV2ZWwvTGlmZWN5Y2xlLzQ"
      + index       = 4
      + name        = "Generally Available"
    }

```

2024-03-26 19:45 UTC, taimoorgit commented
Index filter also works:

```
data "opslevel_lifecycle" "l3" {
  filter {
    field = "index"
    value = "4"
  }
}

```

```
  + o3 = {
      + alias       = "generally_available"
      + description = "Service is supporting features available to be used by all customers, and should be fully stable."
      + filter      = {
          + field = "id"
          + value = "Z2lkOi8vb3BzbGV2ZWwvTGlmZWN5Y2xlLzQ"
        }
      + id          = "Z2lkOi8vb3BzbGV2ZWwvTGlmZWN5Y2xlLzQ"
      + index       = 4
      + name        = "Generally Available"
    }

```

2024-03-26 19:49 UTC, davidbloss commented on tests/mock_datasource/lifecycle.tfmock.hcl
> +  defaults = {
```suggestion
  defaults = {
    alias = "Lifecycle Alias"
```

2024-03-26 19:51 UTC, davidbloss commented on opslevel/datasource_opslevel_lifecycle.go
> +func (sys *LifecycleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
Spotted some copy pasta 🍝  `sys` maybe could be `d` or something

2024-03-26 19:52 UTC, davidbloss commented on opslevel/datasource_opslevel_lifecycle.go
> +func filterLifecycles(tiers []opslevel.Lifecycle, filter FilterBlockModel) (*opslevel.Lifecycle, error) {
Moar copy pasta 🍝  `tiers` --> `lifecycles`

2024-03-26 19:55 UTC, davidbloss requested changes
Overall looks good! Just needs a few tweaks

2024-03-26 20:39 UTC, davidbloss commented on tests/datasource_lifecycle.tftest.hcl
> +    error_message = "id in opslevel_lifecycle mock was not set"
```suggestion
    error_message = "wrong alias in opslevel_lifecycle mock"
```

2024-03-26 20:39 UTC, davidbloss commented on tests/datasource_lifecycle.tftest.hcl
> +    error_message = "id in opslevel_lifecycle mock was not set"
```suggestion
    error_message = "wrong alias in opslevel_lifecycle mock"
```

2024-03-26 20:40 UTC, davidbloss commented on tests/datasource_lifecycle.tftest.hcl
> +    error_message = "id in opslevel_lifecycle mock was not set"
```suggestion
    error_message = "wrong alias in opslevel_lifecycle mock"
```

2024-03-26 20:40 UTC, davidbloss commented on tests/datasource_lifecycle.tftest.hcl
> +    condition     = data.opslevel_lifecycle.index_filter.alias == "generally_available"
```suggestion
    error_message = "wrong alias in opslevel_lifecycle mock"
```

2024-03-26 20:41 UTC, davidbloss commented on tests/datasource_lifecycle.tftest.hcl
> +    error_message = "id in opslevel_lifecycle mock was not set"
Under the hood, these four `assert { }` blocks are all testing the same `.alias` field defined in `tests/mock_datasource/lifecycle.tfmock.hcl`

2024-03-27 13:41 UTC, davidbloss commented
Latest update looks better! I should have check the first time but there is no `description` field in our current [lifecycle datasource](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/data-sources/lifecycle), or in the old code

2024-03-27 13:49 UTC, taimoorgit commented
> Latest update looks better! I should have check the first time but there is no `description` field in our current [lifecycle datasource](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/data-sources/lifecycle), or in the old code

Just pushed a change to remove description

2024-03-27 15:10 UTC, davidbloss approved these changes
LGTM! 🎉

2024-03-27 15:15 UTC, merged