add team datasource
OpsLevel/terraform-provider-opslevel pull request #242
Opened 2024-03-26 20:32 UTC by taimoorgit

## Issues

https://github.com/OpsLevel/team-platform/issues/288

## Tophatting

2024-03-27 21:04 UTC, rocktavious requested changes
LGTM - but please wait for @davidbloss to give final say since he's ALOT closer to the codebase than me now.

2024-03-28 13:25 UTC, davidbloss commented on opslevel/datasource_opslevel_team.go
> +func membershipsToListValue(ctx context.Context, members *opslevel.TeamMembershipConnection) basetypes.ListValue {
```suggestion
func membershipsToListValue(members *opslevel.TeamMembershipConnection) basetypes.ListValue {
```
`ctx` is unused

2024-03-28 13:26 UTC, davidbloss commented on opslevel/datasource_opslevel_team.go
> +func membershipsToListValue(ctx context.Context, members *opslevel.TeamMembershipConnection) basetypes.ListValue {
This update would allow the following update below...

2024-03-28 13:27 UTC, davidbloss commented on opslevel/datasource_opslevel_team.go
> +		Members:     membershipsToListValue(ctx, team.Memberships),
```suggestion
		Members:     membershipsToListValue(team.Memberships),
```
After func signature update above

2024-03-28 13:27 UTC, davidbloss commented on opslevel/datasource_opslevel_team.go
> +func NewTeamDataSourceModel(ctx context.Context, team opslevel.Team) TeamDataSourceModel {
```suggestion
func NewTeamDataSourceModel(team opslevel.Team) TeamDataSourceModel {
```
Related to others

2024-03-28 13:34 UTC, davidbloss commented on opslevel/datasource_opslevel_team.go
> +		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("unable to read team datasource, got error: %s", err))
```suggestion
		resp.Diagnostics.AddError("Config Error", "'alias' or 'id' for opslevel_team datasource must be set")
```
`err` here is not set

2024-03-28 13:41 UTC, davidbloss commented on opslevel/datasource_opslevel_team.go
> +	} else if data.Id.ValueString() != "" {
```suggestion
	} else if !opslevel.IsID(data.Id.ValueString()) {
```
Alternatively could go first in the if else chain if `if opslevel.IsID(data.Id.ValueString()) {` is easier to read

2024-03-28 14:00 UTC, rocktavious approved these changes

2024-03-28 19:10 UTC, davidbloss approved these changes
LGTM! 🎉

2024-03-28 19:10 UTC, merged