WIP fixing default values and null from tf config
OpsLevel/terraform-provider-opslevel pull request #245
Opened 2024-03-28 21:41 UTC by davidbloss

## Issues

## Changelog

- [ ] List your changes here
- [ ] Make a `changie` entry

## Tophatting

2024-04-02 21:06 UTC, davidbloss commented
There is a known issue during the update of this resource around `provider_data`. We can't unset it after it's set. I plan on writing a custom error message letting customers know that we know about this and are fixing it at some point.

2024-04-03 13:50 UTC, taimoorgit requested changes
I have questions

2024-04-03 13:50 UTC, taimoorgit commented on tests/mock_resource/infra.tfmock.hcl
I think we are going to end up with a lot of files less than 5 lines long that should be combined into one - can we just make a mock_resource.tfmock.hcl?

2024-04-03 13:50 UTC, taimoorgit commented on opslevel/resource_opslevel_infra.go
> +		infraInput.Owner = opslevel.NewID("")
This makes sense to me, since owner will marshal into `null`.

2024-04-03 13:50 UTC, taimoorgit commented on opslevel/resource_opslevel_infra.go
> +		newJSON, err := opslevel.NewJSON("{}")
Can you elaborate on what `"{}"` will do? 

```
type InfraInput struct {
	Schema   string              `json:"schema" yaml:"schema" default:"Database"`
	Owner    *ID                 `json:"owner,omitempty" yaml:"owner,omitempty" default:"XXX_owner_id_XXX"`
	Provider *InfraProviderInput `json:"provider" yaml:"provider"`
	Data     *JSON               `json:"data" yaml:"data" default:"{\"name\":\"my-big-query\",\"engine\":\"BigQuery\",\"endpoint\":\"https://google.com\",\"replica\":false}"`
}
```

Could we just exclude the `Data` field if it was not set?

2024-04-03 14:46 UTC, taimoorgit commented on opslevel/resource_opslevel_infra.go
> +		newJSON, err := opslevel.NewJSON("{}")
In this case, we want to send the API `"{}"` (on json marshal) and the API will deal with it correctly.

2024-04-03 14:53 UTC, taimoorgit approved these changes

2024-04-03 15:43 UTC, merged